#!/usr/bin/env bash

node_configure()
{
  if os_is_linux
  then
    if python=$(command -v python2)
    then
      replace_content "#!/usr/bin/env python" \
        with "#!${python}" in "tools/waf-light"

      replace_content "python " with "${python} " in "Makefile"
    fi
  fi

  ./configure --prefix="${install_path}"
}

